#!/usr/bin/env bash

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  READ THE ZPROJECT/README.MD FOR INFORMATION ABOUT MAKING PERMANENT CHANGES. #
################################################################################
# Note: This file is customized (zip not present in our containers)

set -x
set -e

if [ "$BUILD_TYPE" == "default" ]; then
    # Tell travis to deploy all files in dist
    mkdir dist
    export FTY_ALERT_ENGINE_DEPLOYMENT=dist/*
    # Move archives to dist
    mv *.tar.gz dist
    mv *.zip dist || true
    # Generate hash sums
    cd dist
    md5sum *.zip *.tar.gz > MD5SUMS || true
    sha1sum *.zip *.tar.gz > SHA1SUMS || true
    cd -
elif [ "$BUILD_TYPE" == "bindings" ] && [ "$BINDING" == "jni" ]; then
    ( cd bindings/jni && TERM=dumb PKG_CONFIG_PATH=/tmp/lib/pkgconfig ./gradlew clean bintrayUpload )
    cp bindings/jni/android/fty_alert_engine-android.jar fty_alert_engine-android-1.0.0.jar
    export FTY_ALERT_ENGINE_DEPLOYMENT=fty_alert_engine-android-1.0.0.jar
else
    export FTY_ALERT_ENGINE_DEPLOYMENT=""
fi
