################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_FTY_SHM "libfty_shm")
    if (NOT PC_FTY_SHM_FOUND)
        pkg_check_modules(PC_FTY_SHM "libfty_shm")
    endif (NOT PC_FTY_SHM_FOUND)
    if (PC_FTY_SHM_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_FTY_SHM_CFLAGS} ${PC_FTY_SHM_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_FTY_SHM_INCLUDE_HINTS ${PC_FTY_SHM_INCLUDE_DIRS} ${PC_FTY_SHM_INCLUDE_DIRS}/*)
        set(PC_FTY_SHM_LIBRARY_HINTS ${PC_FTY_SHM_LIBRARY_DIRS} ${PC_FTY_SHM_LIBRARY_DIRS}/*)
    endif(PC_FTY_SHM_FOUND)
endif (NOT MSVC)

find_path (
    FTY_SHM_INCLUDE_DIRS
    NAMES fty_shm.h
    HINTS ${PC_FTY_SHM_INCLUDE_HINTS}
)

find_library (
    FTY_SHM_LIBRARIES
    NAMES fty_shm
    HINTS ${PC_FTY_SHM_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    FTY_SHM
    REQUIRED_VARS FTY_SHM_LIBRARIES FTY_SHM_INCLUDE_DIRS
)
mark_as_advanced(
    FTY_SHM_FOUND
    FTY_SHM_LIBRARIES FTY_SHM_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
