################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LUA-5.1 "lua")
    if (NOT PC_LUA-5.1_FOUND)
        pkg_check_modules(PC_LUA-5.1 "lua")
    endif (NOT PC_LUA-5.1_FOUND)
    if (PC_LUA-5.1_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_LUA-5.1_CFLAGS} ${PC_LUA-5.1_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LUA-5.1_INCLUDE_HINTS ${PC_LUA-5.1_INCLUDE_DIRS} ${PC_LUA-5.1_INCLUDE_DIRS}/*)
        set(PC_LUA-5.1_LIBRARY_HINTS ${PC_LUA-5.1_LIBRARY_DIRS} ${PC_LUA-5.1_LIBRARY_DIRS}/*)
    endif(PC_LUA-5.1_FOUND)
endif (NOT MSVC)

find_path (
    LUA-5.1_INCLUDE_DIRS
    NAMES lua.h
    HINTS ${PC_LUA-5.1_INCLUDE_HINTS}
)

find_library (
    LUA-5.1_LIBRARIES
    NAMES lua
    HINTS ${PC_LUA-5.1_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LUA-5.1
    REQUIRED_VARS LUA-5.1_LIBRARIES LUA-5.1_INCLUDE_DIRS
)
mark_as_advanced(
    LUA-5.1_FOUND
    LUA-5.1_LIBRARIES LUA-5.1_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
