################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_FTY-COMMON "libfty_common")
    if (NOT PC_FTY-COMMON_FOUND)
        pkg_check_modules(PC_FTY-COMMON "libfty_common")
    endif (NOT PC_FTY-COMMON_FOUND)
    if (PC_FTY-COMMON_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_FTY-COMMON_CFLAGS} ${PC_FTY-COMMON_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_FTY-COMMON_INCLUDE_HINTS ${PC_FTY-COMMON_INCLUDE_DIRS} ${PC_FTY-COMMON_INCLUDE_DIRS}/*)
        set(PC_FTY-COMMON_LIBRARY_HINTS ${PC_FTY-COMMON_LIBRARY_DIRS} ${PC_FTY-COMMON_LIBRARY_DIRS}/*)
    endif(PC_FTY-COMMON_FOUND)
endif (NOT MSVC)

find_path (
    FTY-COMMON_INCLUDE_DIRS
    NAMES fty_common.h
    HINTS ${PC_FTY-COMMON_INCLUDE_HINTS}
)

find_library (
    FTY-COMMON_LIBRARIES
    NAMES fty-common
    HINTS ${PC_FTY-COMMON_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    FTY-COMMON
    REQUIRED_VARS FTY-COMMON_LIBRARIES FTY-COMMON_INCLUDE_DIRS
)
mark_as_advanced(
    FTY-COMMON_FOUND
    FTY-COMMON_LIBRARIES FTY-COMMON_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
