/*  =========================================================================
    fty_alert_engine_classes - private header file

    Copyright (C) 2019 - 2019 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_ALERT_ENGINE_CLASSES_H_INCLUDED
#define FTY_ALERT_ENGINE_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/fty-alert-engine.h"

//  Extra headers
#include "database.h"
#include "asset_database.h"
#include "rule_factory.h"

//  Opaque class structures to allow forward references
#ifndef ASSET_T_DEFINED
typedef struct _asset_t asset_t;
#define ASSET_T_DEFINED
#endif
#ifndef RULE_T_DEFINED
typedef struct _rule_t rule_t;
#define RULE_T_DEFINED
#endif
#ifndef LUA_EVALUATE_T_DEFINED
typedef struct _lua_evaluate_t lua_evaluate_t;
#define LUA_EVALUATE_T_DEFINED
#endif
#ifndef EXTENDED_RULES_T_DEFINED
typedef struct _extended_rules_t extended_rules_t;
#define EXTENDED_RULES_T_DEFINED
#endif
#ifndef ALERT_T_DEFINED
typedef struct _alert_t alert_t;
#define ALERT_T_DEFINED
#endif
#ifndef HEADER_TESTS_T_DEFINED
typedef struct _header_tests_t header_tests_t;
#define HEADER_TESTS_T_DEFINED
#endif

//  Internal API

#include "asset.h"
#include "rule.h"
#include "lua_evaluate.h"
#include "extended_rules.h"
#include "alert.h"
#include "header_tests.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef FTY_ALERT_ENGINE_BUILD_DRAFT_API

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_ALERT_ENGINE_PRIVATE void
    asset_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_ALERT_ENGINE_PRIVATE void
    rule_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_ALERT_ENGINE_PRIVATE void
    lua_evaluate_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_ALERT_ENGINE_PRIVATE void
    extended_rules_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_ALERT_ENGINE_PRIVATE void
    alert_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
FTY_ALERT_ENGINE_PRIVATE void
    header_tests_test (bool verbose);

//  Self test for private classes
FTY_ALERT_ENGINE_PRIVATE void
    fty_alert_engine_private_selftest (bool verbose, const char *subtest);

#endif // FTY_ALERT_ENGINE_BUILD_DRAFT_API

#endif
